### ISSUE TITLE
重疊地點無法點開查看

### ISSUE THREAD

**Issue by Sea-n** [kiang/air_raid_shelter#1]
如新竹交通大學 ([Google Maps](https://goo.gl/maps/8DTJTMziUurpAF1e8))，同個地點有 31 筆資料
![image](https://user-images.githubusercontent.com/10102616/183658433-ca39ce96-858f-4d9c-97ad-d6c21c6fc995.png)

點擊時頁面會放到最大，但因為完全重疊而無法點開
![image](https://user-images.githubusercontent.com/10102616/183658881-68f2080b-c687-452d-8168-64827b6e0554.png)

**Comment by kiang** [comment]
嘗試加入了一點效果，現在單點重複的部份會展開虛擬點，點選個別虛擬點可以看到資料

**Comment by Sea-n** [comment]
非常感謝！
